#!/usr/bin/env python3
"""Measure throughput at a fixed max_num_seqs (baseline vLLM only).

Workload:
  - Pool = wildchat 2000 + lmsys 2000 (conversation_only=True, exclude_code=True,
    dataset_seed=42). Same as exp/run_sslo new flow.
  - num_prompts = max_num_seqs * 4. Drawn from pool (without replacement,
    deterministic via --sampling-seed).
  - All requests submitted at t0 (burst, no Poisson).

Measurement window:
  - Sort completed requests by completion wall-clock.
  - window_start = completion_ts of the base_n-th finisher (1-indexed).
  - window_end   = completion_ts of the (3*base_n)-th finisher.
  - Throughput = (tokens generated by the 2*base_n requests inside the window)
                 / (window_end - window_start).
  - Reasoning: skip the first base_n as warmup (engine ramp-up),
    measure on the next 2*base_n, leaving a base_n tail outside the window.

Output: <output_dir>/result.json with the metrics, plus per-request rows
for inspection.
"""
from __future__ import annotations

import argparse
import asyncio
import gc
import json
import os
import random as _random
import sys
import time
from pathlib import Path
from typing import Any

import torch

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "tools"))
from lm_datasets import _load_wildchat, _load_lmsys  # noqa: E402


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--model", required=True)
    p.add_argument("--max-num-seqs", type=int, required=True)
    p.add_argument("--tensor-parallel-size", type=int, default=1)
    p.add_argument("--gpu-memory-utilization", type=float, default=0.95)
    p.add_argument("--max-model-len", type=int, default=0)
    p.add_argument("--generation-max-tokens", type=int, default=2048)
    p.add_argument("--output-dir", required=True)
    p.add_argument("--dataset-seed", type=int, default=42)
    p.add_argument("--sampling-seed", type=int, default=43)
    return p.parse_args()


def build_pool(dataset_seed: int) -> list[str]:
    wildchat = _load_wildchat(
        split="train", num_prompts=2500, exclude_code=True,
        conversation_only=True)[:2000]
    lmsys = _load_lmsys(
        split="train", num_prompts=2500, exclude_code=True,
        conversation_only=True)[:2000]
    combined = wildchat + lmsys
    _random.Random(dataset_seed).shuffle(combined)
    assert len(combined) == 4000, f"pool size {len(combined)}"
    return combined


def apply_chat_template(prompts: list[str], model: str) -> list[str]:
    from transformers import AutoTokenizer
    tok = AutoTokenizer.from_pretrained(model, trust_remote_code=True)
    out = []
    for p in prompts:
        out.append(tok.apply_chat_template(
            [{"role": "user", "content": p}],
            tokenize=False,
            add_generation_prompt=True,
            enable_thinking=False,
        ))
    return out


async def collect_one(engine, idx: int, prompt: str, params) -> dict[str, Any]:
    request_id = str(idx)
    last_output = None
    submit_ts = time.time()
    async for output in engine.generate(prompt, params, request_id=request_id):
        last_output = output
    complete_ts = time.time()
    if last_output is None:
        return {"idx": idx, "submit_ts": submit_ts, "complete_ts": complete_ts,
                "num_output_tokens": 0}
    metrics = getattr(last_output, "metrics", None)
    num_gen = int(getattr(metrics, "num_generation_tokens", 0) or 0) if metrics else 0
    return {
        "idx": idx,
        "submit_ts": submit_ts,
        "complete_ts": complete_ts,
        "num_output_tokens": num_gen,
        "num_prompt_tokens": getattr(metrics, "num_prompt_tokens", None) if metrics else None,
    }


async def run() -> None:
    args = parse_args()
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    base_n = args.max_num_seqs
    num_prompts = base_n * 4

    print(f"[batch={base_n}] building pool")
    pool = build_pool(args.dataset_seed)
    rng = _random.Random(args.sampling_seed)
    indices = rng.sample(range(len(pool)), num_prompts)
    prompts = [pool[i] for i in indices]
    print(f"[batch={base_n}] applying chat template for {len(prompts)} prompts")
    prompts = apply_chat_template(prompts, args.model)

    from vllm import AsyncLLMEngine, SamplingParams
    from vllm.engine.arg_utils import AsyncEngineArgs

    engine_kwargs: dict[str, Any] = dict(
        model=args.model,
        max_num_seqs=base_n,
        tensor_parallel_size=args.tensor_parallel_size,
        gpu_memory_utilization=args.gpu_memory_utilization,
        enable_log_requests=False,
        generation_config="auto",
        language_model_only=True,
        sslo_params={"chunk_unit": "sentence", "seconds_per_word": 0.28,
                     "method": "baseline"},
    )
    if args.max_model_len > 0:
        engine_kwargs["max_model_len"] = args.max_model_len
    engine_args = AsyncEngineArgs(**engine_kwargs)
    engine = AsyncLLMEngine.from_engine_args(engine_args)

    sampling_kwargs = {
        "temperature": 0.7, "top_p": 0.8, "top_k": 20, "min_p": 0.0,
        "presence_penalty": 1.5, "repetition_penalty": 1.0,
        "max_tokens": args.generation_max_tokens,
    }
    sp_base = SamplingParams.from_optional(**sampling_kwargs)

    def per_req_params(seed: int):
        p = sp_base.clone()
        p.seed = seed
        return p

    try:
        run_started = time.time()
        t0 = time.monotonic()
        tasks = [
            asyncio.create_task(collect_one(engine, i, prompts[i], per_req_params(i)))
            for i in range(num_prompts)
        ]
        rows = await asyncio.gather(*tasks)
        elapsed = time.monotonic() - t0
        run_ended = time.time()

        # Sort completions for window slicing.
        rows_sorted = sorted(rows, key=lambda r: r["complete_ts"])
        # 1-indexed: base_n-th = rows_sorted[base_n-1], (3*base_n)-th = rows_sorted[3*base_n-1]
        if len(rows_sorted) < 3 * base_n:
            raise RuntimeError(
                f"not enough completions: have {len(rows_sorted)}, need {3*base_n}")
        win_start_ts = rows_sorted[base_n - 1]["complete_ts"]
        win_end_ts   = rows_sorted[3 * base_n - 1]["complete_ts"]
        win_rows = rows_sorted[base_n - 1: 3 * base_n - 1 + 1]
        # 2*base_n + 1 includes both endpoints; use [base_n : 3*base_n] for the
        # 2*base_n "between" reqs (open at start, closed at end).
        win_inside = rows_sorted[base_n: 3 * base_n]
        win_dur = win_end_ts - win_start_ts
        tokens_inside = sum(r["num_output_tokens"] for r in win_inside)
        result = {
            "model": args.model,
            "max_num_seqs": base_n,
            "tensor_parallel_size": args.tensor_parallel_size,
            "num_prompts": num_prompts,
            "completed": len(rows_sorted),
            "run_started_ts": run_started,
            "run_ended_ts": run_ended,
            "run_elapsed_s": elapsed,
            "window_start_ts": win_start_ts,
            "window_end_ts": win_end_ts,
            "window_duration_s": win_dur,
            "window_request_count": len(win_inside),
            "window_total_output_tokens": tokens_inside,
            "throughput_tokens_per_second": (tokens_inside / win_dur) if win_dur > 0 else 0,
            "throughput_req_per_second": (len(win_inside) / win_dur) if win_dur > 0 else 0,
        }
        (output_dir / "result.json").write_text(json.dumps(result, indent=2) + "\n")
        with (output_dir / "requests.jsonl").open("w") as f:
            for r in rows_sorted:
                f.write(json.dumps(r) + "\n")
        print(f"[batch={base_n}] tokens/s={result['throughput_tokens_per_second']:.1f} "
              f"req/s={result['throughput_req_per_second']:.2f} "
              f"win_dur={win_dur:.2f}s")
    finally:
        engine.shutdown()
        del engine
        gc.collect()
        try:
            if torch.cuda.is_available():
                torch.cuda.empty_cache()
                torch.cuda.synchronize()
        except Exception:
            pass
        time.sleep(2)


def main() -> None:
    asyncio.run(run())


if __name__ == "__main__":
    main()
